name: Deploy to AWS S3

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa your-s3-bucket-name.s3.amazonaws.com >> ~/.ssh/known_hosts

    - name: Upload to S3
      run: scp -r ./* your-s3-bucket-name:/milesdawbucket
